// unamblify — Copyright (c) 2026 Rob Ludwick.
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU Affero General Public License v3.0 only. See LICENSE.

//! The garbage tail of a key-down example (`docs/design/training.md`,
//! "The edges matter most"): what a receiver produces after the carrier
//! drops, with a silence target. One implementation for the shard builder
//! and the on-the-fly loader, so a `source = "shards"` run and a
//! `source = "pipeline"` run train against the same distribution.

use crate::FRAME_SAMPLES;
use crate::rng::Rng;

/// Kinds of receiver garbage, drawn uniformly per tail example.
pub const GARBAGE_KINDS: usize = 4;

/// `len` samples at 8 kHz of receiver garbage around `rms`: one of white
/// noise, the last frame repeated, gated noise bursts, or lowpass rumble —
/// chosen and generated by `rng`. `last_frame` is the final frame of real
/// speech (empty = white noise replaces the repeat kind).
#[must_use]
pub fn garbage_tail(rng: &mut Rng, len: usize, rms: f32, last_frame: &[f32]) -> Vec<f32> {
    let rms = rms.max(1e-3);
    match rng.below(GARBAGE_KINDS) {
        0 => (0..len).map(|_| rng.normal() * rms).collect(),
        1 if !last_frame.is_empty() => (0..len).map(|i| last_frame[i % last_frame.len()]).collect(),
        2 => {
            let mut on = false;
            (0..len)
                .map(|i| {
                    if i % FRAME_SAMPLES == 0 {
                        on = rng.chance(0.5);
                    }
                    if on { rng.normal() * rms * 1.5 } else { 0.0 }
                })
                .collect()
        }
        _ => {
            let mut y = 0.0f32;
            (0..len)
                .map(|_| {
                    y = 0.95 * y + 0.05 * rng.normal() * rms * 4.0;
                    y
                })
                .collect()
        }
    }
}

/// RMS of `x` (0 for empty input).
#[must_use]
pub fn rms(x: &[f32]) -> f32 {
    if x.is_empty() {
        return 0.0;
    }
    #[allow(clippy::cast_precision_loss)]
    let ms = x.iter().map(|v| v * v).sum::<f32>() / x.len() as f32;
    ms.sqrt()
}

/// Turn a cropped pair into a tail example in place: speech ends at
/// `speech_end8` (8 kHz samples, a frame boundary); from there `deg8` is
/// filled with [`garbage_tail`] at the speech's level and `clean16` with
/// zeros. Returns the mask boundary (a 16 kHz sample index).
pub fn fill_tail(
    deg8: &mut [f32],
    clean16: &mut [f32],
    speech_end8: usize,
    rng: &mut Rng,
) -> usize {
    let speech_end8 = speech_end8.min(deg8.len());
    let level = rms(&deg8[..speech_end8]);
    let last_frame_start = speech_end8.saturating_sub(FRAME_SAMPLES);
    let last_frame = deg8[last_frame_start..speech_end8].to_vec();
    let garbage = garbage_tail(rng, deg8.len() - speech_end8, level, &last_frame);
    deg8[speech_end8..].copy_from_slice(&garbage);
    let boundary = (2 * speech_end8).min(clean16.len());
    for v in &mut clean16[boundary..] {
        *v = 0.0;
    }
    boundary
}

#[cfg(test)]
#[allow(clippy::float_cmp, clippy::cast_precision_loss)]
mod tests {
    use super::*;

    #[test]
    fn garbage_variants_are_the_right_length_and_finite() {
        let mut r = Rng::new(1);
        let frame = vec![0.1f32; FRAME_SAMPLES];
        let mut kinds_seen = [false; GARBAGE_KINDS];
        for _ in 0..32 {
            let probe = r.clone();
            let g = garbage_tail(&mut r, 1600, 0.05, &frame);
            assert_eq!(g.len(), 1600);
            assert!(g.iter().all(|v| v.is_finite()));
            kinds_seen[probe.clone().below(GARBAGE_KINDS)] = true;
        }
        assert!(kinds_seen.iter().all(|&k| k), "{kinds_seen:?}");
        // No last frame: the repeat kind falls through to rumble.
        let g = garbage_tail(&mut Rng::new(5), 320, 0.05, &[]);
        assert_eq!(g.len(), 320);
    }

    #[test]
    fn fill_tail_masks_clean_and_fills_deg_with_garbage() {
        let mut deg8: Vec<f32> = (0..1600).map(|i| ((i % 7) as f32 - 3.0) * 0.1).collect();
        let mut clean16 = vec![0.5f32; 3200];
        let b = fill_tail(&mut deg8, &mut clean16, 800, &mut Rng::new(2));
        assert_eq!(b, 1600);
        assert!(clean16[..1600].iter().all(|&v| v == 0.5));
        assert!(clean16[1600..].iter().all(|&v| v == 0.0));
        assert!(
            deg8[800..].iter().any(|&v| v != 0.0),
            "tail is garbage, not silence"
        );
        assert_eq!(rms(&[]), 0.0);
        assert!((rms(&[3.0, 4.0]) - (12.5f32).sqrt()).abs() < 1e-6);
    }
}
